### ISSUE TITLE
How long should image editing/generation take?

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [salesforce/EDICT#1]
Hi, first of all thanks for open sourcing the code for your paper!

How long should image generation take with this method? On a free Colab session (Tesla T4) I'm averaging 21.9s/it. On image translation, 40 steps takes me around 14:31s (so that's around 29m 2s for the whole thing); and on basic image generation, 50 steps takes me around 18m 20s. Are these the numbers I should be expecting?

Thank you again!

Edit: GPU was a T4, not a K80

**Comment by bram-w** [comment]
Hi Ryan, thanks for your interest in our paper! Sorry I didn't see this earlier.

We ran/run experiments on a A100-SXM4-40GB for `EDICT.ipynb`. Looking at this link https://developer.nvidia.com/deep-learning-performance-training-inference it seems that we should expect a ~7x speed difference between that and the T4, so EDICT generations taking ~5 minutes, edits taking ~10 minutes. Seems like things are off by about a factor of 3 from expected given the GPUs.

Unfortunately my hardware knowledge isn't the most extensive, so I'm not sure where the 3x factor comes from, but most of that slowdown looks attributable to the accelerator like you suggested.

For comparison experiments of course using the full precision/steps setting is recommended, but depending on your application/prototyping goal you should still be able to get good editing results faster by doing some combination of 
1) Reducing the number of steps (iirc `steps=20` lowers quality a bit but it still pretty good) and
2) Reducing the precision from double to half (less stable but still works)

2) Isn't available in the code base currently, but we've used it in experiments some. This will be a good thing for me to add after the ICML deadline, setting myself a reminder to do that. In the meantime, if you want to implement it you could

Make another directory called `my_half_diffusers` and follow the below diff 
```
diff my_diffusers/ my_half_diffusers/ -r
diff -r my_diffusers/models/attention.py my_half_diffusers/models/attention.py
77c77
<         attention_probs = torch.softmax(attention_scores.double(), dim=-1).type(attention_scores.dtype)
---
>         attention_probs = torch.softmax(attention_scores, dim=-1).type(attention_scores.dtype)
diff -r my_diffusers/models/embeddings.py my_half_diffusers/models/embeddings.py
41c41
<     exponent = -math.log(max_period) * torch.arange(start=0, end=half_dim, dtype=torch.float64)
---
>     exponent = -math.log(max_period) * torch.arange(start=0, end=half_dim, dtype=torch.float32)
45c45
<     emb = timesteps[:, None].double() * emb[None, :]
---
>     emb = timesteps[:, None] * emb[None, :]
60c60
<     return emb
---
>     return emb.to(torch.float16)
Only in my_half_diffusers/models: __pycache__
diff -r my_diffusers/models/resnet.py my_half_diffusers/models/resnet.py
137c137
<         kernel = np.asarray(kernel, dtype=np.float64)
---
>         kernel = np.asarray(kernel, dtype=np.float16)
222c222
<         kernel = np.asarray(kernel, dtype=np.float64)
---
>         kernel = np.asarray(kernel, dtype=np.float16)
336c336
<         hidden_states = self.norm1(hidden_states.double()).type(hidden_states.dtype)
---
>         hidden_states = self.norm1(hidden_states).type(hidden_states.dtype)
354c354
<         hidden_states = self.norm2(hidden_states.double()).type(hidden_states.dtype)
---
>         hidden_states = self.norm2(hidden_states).type(hidden_states.dtype)
394c394
<     kernel = np.asarray(kernel, dtype=np.float64)
---
>     kernel = np.asarray(kernel, dtype=np.float16)
428c428
<     kernel = np.asarray(kernel, dtype=np.float64)
---
>     kernel = np.asarray(kernel, dtype=np.float16)
diff -r my_diffusers/models/unet_2d_condition.py my_half_diffusers/models/unet_2d_condition.py
218c218
<             timesteps = timesteps.to(dtype=torch.float64)
---
>             timesteps = timesteps.to(dtype=torch.float16)
266c266
<         sample = self.conv_norm_out(sample.double()).type(sample.dtype)
---
>         sample = self.conv_norm_out(sample).type(sample.dtype)
diff -r my_diffusers/models/unet_2d.py my_half_diffusers/models/unet_2d.py
232c232
<         sample = self.conv_norm_out(sample.double()).type(sample.dtype)
---
>         sample = self.conv_norm_out(sample).type(sample.dtype)

```

Add the imports from the new dir here (https://github.com/salesforce/EDICT/blob/main/edict_functions.py#L25). That can be done either by hardcoding or adding a flag like `use_half_prec`

Remove the data type casting at https://github.com/salesforce/EDICT/blob/main/edict_functions.py#L52
```
unet.double().to(device)
vae.double().to(device)
clip.double().to(device)
```

Change instances of float64 to float16
```
grep float64 *py
        init_image = np.array(init_image).astype(np.float64) / 255.0 * 2.0 - 1.0
        prev_image = np.array(prev_image).astype(np.float64) / 255.0 * 2.0 - 1.0
            im = np.array(im).astype(np.float64) / 255.0 * 2.0 - 1.0
                           dtype=torch.float64)
```


Hope that those comments help! Leaving this issue open to continue discussion. Sorry to give instructions rather than a PR code fix for now; like I said I have a note for myself to add this at the end of January after ICML.

**Comment by ryan-caesar-ramos** [comment]
Hi Dr. Wallace, thanks again for your detailed follow-up! Please don't worry about not releasing a PR, and have fun with ICML.

Just wondering though, can you confirm that these changes run without errors? I made the changes but have spent the past few days debugging, mostly regarding errors about dtypes (e.g. matrices not being the same dtype, certain operations expecting Half's but getting Float's). I'll keep debugging of course, but it would be nice to know that the code should work at the end of all this.

Thanks again!

**Comment by bram-w** [comment]
Hi Ryan, super glad it's working! Nice job working through the `diffusers` edits, I know from experience that the data types are a bit of a rat nest in there. 

I'll close this for now but feel free to re-open if you have dtype-related questions.

PS And ICML is fun so far! Afterwards we should have some fun new functionality for this repo
