### ISSUE TITLE
unditional DDIM in fig 2

### ISSUE THREAD

**Issue by JunMa11** [salesforce/EDICT#2]
Dear all,

Thanks for sharing the awesome work!

Would it be possible for you to share a jupyter-notebook to reproduce the unconditional DDIM  results in Fig 2?

**Comment by bram-w** [comment]
Leaving this open for now since I can put in a more formal version of this code but for those wondering about this here's a way to do it
<img width="1309" alt="Screen Shot 2023-01-18 at 3 13 25 PM" src="https://user-images.githubusercontent.com/98437098/213315758-f27435b9-be3c-41be-9e12-d1eb2ee1688f.png">

**Comment by bram-w** [comment]
Commited the recon function (not tested but should be fine, re-open if issue) https://github.com/salesforce/EDICT/commit/6d7044423b8263517ac77e7725ccaf3abf678ef7

**Comment by zzzzzx-1115** [comment]
@bram-w Hello, I have the same problem about the 3th and 4th column of _Fig 2_:  how do you perform deterministic noising to get the noised $x_T$ which will be used as the starting point of the denoising process? Or say, during this noising process, you use $\varepsilon_{uncondition}$, or $\varepsilon_{condition}$, or $\varepsilon_{uncondition} + w(\varepsilon_{condition}-\varepsilon_{uncondition})$?
